{"version":1,"defects":{"Warning":6,"Tests\\Unit\\RouterTest::it_registers_a_get_router":3,"Tests\\Unit\\RouterTest::it_registers_a_post_router":3,"Tests\\Unit\\RouterTest::there_are_no_routes_when_route_is_created":4,"Error":4,"Tests\\Unit\\RouterTest::test_it_resolves_route":3,"Tests\\Unit\\Services\\InvoiceServiceTest::it_process_invoice":4,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_email_when_invoice_is_processed":3,"Tests\\Unit\\ContainerTest::it_set_a_dependency_class":3,"Tests\\Unit\\ContainerTest::it_gets_a_set_class":4,"Tests\\Unit\\ContainerTest\\ContainerTest::it_throws_a_container_exception_on_resolve_method with data set #0":3},"times":{"Warning":0.186,"Tests\\Unit\\RouterTest::it_registers_a_route":0.194,"Tests\\Unit\\RouterTest::test_it_registers_a_route":0.156,"Tests\\Unit\\RouterTest::it_registers_a_get_router":0,"Tests\\Unit\\RouterTest::it_registers_a_post_router":0,"Tests\\Unit\\RouterTest::there_are_no_routes_when_route_is_created":0.021,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exeption with data set #0":0.062,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exeption with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exeption with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exeption with data set #3":0,"Error":0.028,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":0,"Tests\\Unit\\RouterTest::test_it_resolves_route":0.041,"Tests\\Unit\\Services\\InvoiceServiceTest::it_process_invoice":0.555,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_email_when_invoice_is_processed":0.027,"Tests\\Unit\\ContainerTest::it_set_a_dependency_class":0.184,"Tests\\Unit\\ContainerTest::it_set_a_dependency_interface":0,"Tests\\Unit\\ContainerTest::it_gets_a_set_class":0.026,"Tests\\Unit\\ContainerTest\\ContainerTest::it_throws_a_container_exception_on_resolve_method with data set #0":0.04,"Tests\\Unit\\ContainerTest\\ContainerTest::it_throws_a_container_exception_on_resolve_method with data set #1":0.006,"Tests\\Unit\\ContainerTest\\ContainerTest::it_throws_a_container_exception_on_resolve_method with data set #2":0.006,"Tests\\Unit\\ContainerTest\\ContainerTest::it_set_a_dependency_class":0.115,"Tests\\Unit\\ContainerTest\\ContainerTest::it_set_a_dependency_interface":0}}